language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
script: awesome_bot README.md --allow-dupe --allow-redirect --allow-timeout -t 10 --allow 301,403,404,429,451 --white-list yikm,travis-ci,fashop
notifications:
  email: false
